# Generated by Django 4.1.4 on 2022-12-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Актеры и режисеры',
                'verbose_name_plural': 'Актеры и режисеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Иия')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Слоган')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('year', models.PositiveSmallIntegerField(default=2022, verbose_name='date reales')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('fees_in_kg', models.PositiveIntegerField(default=0, help_text='указывать сумму в доллпрах', verbose_name='Сборы в Кыргызстане')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('actors', models.ManyToManyField(related_name='film_director', to='test2.actor', verbose_name='актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.category', verbose_name='Category')),
                ('genres', models.ManyToManyField(to='test2.actor', verbose_name='жанры')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'film',
            },
        ),
    ]
